logger = Source.Logging.Logger.Default();
%%
mshFolder = Settings.MSH_FOLDER;
surfaceFolder = fullfile(Settings.SURFACE_FOLDER, 'Demo');
mediaFolder = fullfile(Settings.MEDIUM_FOLDER, 'Human');
f = 1.2e6;

media = Source.Physics.Media.FromFolder(logger, mediaFolder, f);
fileName = 'MuscleAndBone';
Source.Geometry.gmsh.Converter.MSHToSurface(...
	fullfile(mshFolder, [fileName '.msh']),...
	fullfile(surfaceFolder, [fileName '.surface']),...
	media);

%%
surfaceFolder = fullfile(Settings.SURFACE_FOLDER, 'Test');
fileName = 'oneCylinder';
Source.Geometry.gmsh.Converter.MSHToSurface(...
	fullfile(mshFolder, [fileName '.msh']),...
	fullfile(surfaceFolder, [fileName '.surface']),...
	media);

%%
surfaceFolder = fullfile(Settings.SURFACE_FOLDER, 'User Committee');
fileName = 'markoil';
Source.Geometry.gmsh.Converter.MSHToSurface(...
	fullfile(mshFolder, [fileName '.msh']),...
	fullfile(surfaceFolder, [fileName '.surface']),...
	media);

%%
mshFolder = fullfile(Settings.MSH_FOLDER, 'User Committee');
surfaceFolder = fullfile(Settings.SURFACE_FOLDER, 'User Committee');
fileName = 'kick-off cylinder';
Source.Geometry.gmsh.Converter.MSHToSurface(...
	fullfile(mshFolder, [fileName '.msh']),...
	fullfile(surfaceFolder, [fileName '.surface']),...
	media);

%%
mshFolder = fullfile(Settings.MSH_FOLDER, 'DBL', '2018', 'Groep 25');
surfaceFolder = fullfile(Settings.SURFACE_FOLDER, 'DBL', '2018', 'Groep 25');
fileName = 'cylindermesh';
Source.Geometry.gmsh.Converter.MSHToSurface(...
	fullfile(mshFolder, [fileName '.msh']),...
	fullfile(surfaceFolder, [fileName '.surface']),...
	media);

%%
mshFolder = fullfile(Settings.MSH_FOLDER, 'Utrecht');
surfaceFolder = fullfile(Settings.SURFACE_FOLDER, 'Utrecht');
mediaFolder = fullfile(Settings.MEDIUM_FOLDER, 'Utrecht');
f = 1.2e6;

media = Source.Physics.Media.FromFolder(logger, mediaFolder, f);
fileName = 'Experiment 1.1';
Source.Geometry.gmsh.Converter.MSHToSurface(...
	fullfile(mshFolder, [fileName '.msh']),...
	fullfile(surfaceFolder, [fileName '.surface']),...
	media);

fileName = 'Experiment 1.1-detailed';
Source.Geometry.gmsh.Converter.MSHToSurface(...
	fullfile(mshFolder, [fileName '.msh']),...
	fullfile(surfaceFolder, [fileName '.surface']),...
	media);